services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: metabase
  #     POSTGRES_PASSWORD: metabase
  #     POSTGRES_DB: metabase
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  metabase-data:
  mongo-data:
  # postgres-data: